# Generated by Django 3.1 on 2020-09-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('TECH', 'Technology'), ('SCI', 'Science'), ('FIN', 'Finace'), ('SPT', 'Sport')], max_length=4),
        ),
    ]
